apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rest-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-rest-api
  template:
    metadata:
      labels:
        app: my-rest-api
    spec:
      containers:
      - name: my-rest-api
        image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<repository_name>:<image_tag>
        ports:
        - containerPort: 5000
