apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rest-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-rest-api
  template:
    metadata:
      labels:
        app: my-rest-api
    spec:
      containers:
      - name: my-rest-api
        image: 635289283142.dkr.ecr.us-east-1.amazonaws.com/my-rest-api
        ports:
        - containerPort: 5000
