name: Deploy to EKS

on:
  push:
    branches:
      - aws-projects

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1
          registry-ids: 635289283142
          mask-password: true
          registry-type: ECR
          skip-logout: false

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.635289283142 }}.dkr.ecr.${{ env.us-east-1 }}.amazonaws.com/${{ env.my-flask-app }}:${{ GITHUB_SHA }} .
          docker push ${{ env.635289283142 }}.dkr.ecr.${{ env.us-east-1 }}.amazonaws.com/${{ env.my-flask-app }}:${{ GITHUB_SHA }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
