name: Deploy to EKS

on:
  push:
    branches:
      - aws-projects
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables for debugging
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "IMAGE_NAME: $IMAGE_NAME"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private
          skip-logout: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          set -e  # Exit on non-zero exit code from commands below
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${IMAGE_NAME}:${{ github.sha }} --push .

      - name: Deploy to EKS
        run: |
          set -e  # Exit on non-zero exit code from commands below
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
