name: Deploy to EKS

on:
  push:
    branches:
      - aws-projects

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private
          skip-logout: false

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          set -e  # Exit on non-zero exit code from commands below
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${IMAGE_NAME}:${{ github.sha }} --push .

      - name: Deploy to EKS
        run: |
          set -e  # Exit on non-zero exit code from commands below
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
